eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-1-server.com:8762/eureka, http://eureka-2-server.com:8763/eureka, http://eureka-3-server.com:8764/eureka
